- name: "brainstorm 🤔"
  color: "f9c74f"
  description: "idea, not fully fleshed out, thinking out loud"
- name: "bug 🐛"
  color: "d50032"
  description: "FIX bug + FIX/ADD missing tests"
- name: "chore 🧹"
  color: "f1c40f"
  description: "Housekeeping, admin, cleanup, etc."
- name: "CICD ⚙️"
  color: "3498db"
  description: "CICD, SRE, DevOps, etc."
- name: "docs 📘"
  color: "2ecc71"
  description: "Improvements or additions to documentation"
- name: "duplicate 👯"
  color: "9b59b6"
  description: "Dupe: This issue or pull request already exists"
- name: "ERROR 🔥"
  color: "e74c3c"
  description: "Production error, crash, functionality down // high priority"
- name: "feature 🎁"
  color: "2ecc71"
  description: "New feature or existing enhancement / improvement"
- name: "question ❓"
  color: "f39c12"
  description: ""
- name: "refactor ♻️"
  color: "f39c12"
  description: ""
- name: "REGRESSION 🚨"
  color: "e67e22"
  description: "FIX current tests + ADD more tests + IMPROVE CICD"
- name: "roadblock 🛑"
  color: "e74c3c"
  description: "stuck / waiting"
- name: "SECURITY 🚨"
  color: "c0392b"
  description: "security risk, issue, opportunity"
- name: "sesh 💬"
  color: "1abc9c"
  description: "discuss / meet / brainstorm / pair program / etc."
- name: "skip 👎"
  color: "95a5a6"
  description: "cancelled, decline, decide against, not doin' it"
- name: "toil 😰"
  color: "c0392b"
  description: "Manual process that needs to be automated"
