name: "Bug Report 🐛"
description: Use this template to report a bug.
title: "[bug]: "
labels: ["bug 🐛"]
assignees: ["username"]

body:
  - type: markdown
    attributes:
      value: "## Bug Report\nThank you for taking the time to report a bug. Please fill out the form below."

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please describe the bug in detail."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Reproduction Steps"
      description: "Please provide step-by-step instructions to reproduce the issue."
      placeholder: |
        1. Step one
        2. Step two
        3. etc

  - type: input
    id: media
    attributes:
      label: "Media/screenshot"
      description: "Upload relevant media/screenshots."

  - type: dropdown
    id: type
    attributes:
      label: "Type"
      description: "Select the type of issue."
      options:
        - "bug"
        - "feature"
        - "enhancement"
    validations:
      required: true
    default: "bug"

  - type: markdown
    attributes:
      value: |
        ## Test Coverage Report

        *To be completed by the committer after implementing the test code.*

  - type: input
    id: coverage_report
    attributes:
      label: "Coverage report/screenshot"
      description: "Upload a screenshot / report showing the new tests written to prevent this bug from happening again later and the 100% passing score from the test run."
