name: Bug Report
description: Use this template to report a bug.
title: "[BUG] Your Bug Title"
labels: ["bug", "needs triage"]
assignees: ["username"]

body:
  - type: markdown
    attributes:
      value: "## Bug Report\nThank you for taking the time to report a bug. Please fill out the form below."

  - type: input
    id: title
    attributes:
      label: "Bug Title"
      description: "Provide a brief title for the bug."
      placeholder: "Enter bug title"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Bug Description"
      description: "Please describe the bug in detail."
      placeholder: "Describe the bug and its impact"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: "Operating System"
      description: "Which operating system are you using?"
      placeholder: "e.g., Windows 10, macOS 11.2"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: "Software Version"
      description: "Which version of the software are you using?"
      options:
        - "1.0.2 (Stable)"
        - "1.0.3 (Beta)"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Reproduction Steps"
      description: "Please provide step-by-step instructions to reproduce the issue."
      placeholder: |
        1. Step one
        2. Step two
        3. ...
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: "Code of Conduct"
      description: "Please agree to the Code of Conduct before submitting."
      options:
        - label: "I agree to follow the Code of Conduct"
          required: true
