name: "Bug 🐛"
description: Use this template to report a bug.
type: Bug
assignees: ["username"]

body:
  - type: markdown
    attributes:
      value: "## Bug Report\nThank you for taking the time to report a bug. Please fill out the form below."

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please describe the bug in detail."
    validations:
      required: true
