name: AI Automation Discovery
description: Submit information about a process you'd like to automate
title: "[Automation]: "
labels: ["automation", "discovery"]
assignees:
  - yourusername

body:
  - type: markdown
    attributes:
      value: |
        ## AI Automation Discovery Form
        Thanks for taking the time to fill out this automation discovery form. This information will help us understand your needs and create an effective automation solution.

  - type: input
    id: company
    attributes:
      label: Company Name
      description: Your organization's name
    validations:
      required: true

  - type: input
    id: contact
    attributes:
      label: Contact Person
      description: Who should we contact about this automation?
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: Email
      description: How can we reach you?
      placeholder: email@example.com
    validations:
      required: true

  - type: input
    id: phone
    attributes:
      label: Phone
      description: Alternative contact method

  - type: markdown
    attributes:
      value: |
        ## Process Overview

  - type: input
    id: process-name
    attributes:
      label: Name of process to automate
      description: What should we call this automation?
    validations:
      required: true

  - type: textarea
    id: process-description
    attributes:
      label: Current process description
      description: Describe how this process works today
      placeholder: Walk us through what happens today...
    validations:
      required: true

  - type: textarea
    id: pain-points
    attributes:
      label: Main pain points
      description: What problems exist with the current process?
      placeholder: What makes this process difficult, time-consuming, or error-prone?
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: How often is this process performed?
      description: Select the frequency that best describes this process
      options:
        - Multiple times daily
        - Daily
        - Weekly
        - Monthly
        - Quarterly
        - Annually
    validations:
      required: true

  - type: input
    id: time-spent
    attributes:
      label: Current time spent on this process
      description: Estimated hours per month
      placeholder: "10"
    validations:
      required: true

  - type: input
    id: people-involved
    attributes:
      label: Number of people involved
      description: How many staff members participate in this process?
      placeholder: "3"
    validations:
      required: true

  - type: input
    id: direct-costs
    attributes:
      label: Estimated direct costs
      description: Annual costs associated with this process ($)
      placeholder: "5000"

  - type: markdown
    attributes:
      value: |
        ## Process Details

  - type: textarea
    id: workflow-steps
    attributes:
      label: Step-by-step workflow
      description: List each step in the current process
      placeholder: |
        1. 
        2. 
        3. 
        4. 
        5. 
    validations:
      required: true

  - type: textarea
    id: human-judgment
    attributes:
      label: Decisions requiring human judgment
      description: What decisions in this process require human input?
      placeholder: Which parts of the process require expertise, judgment, or approval?
    validations:
      required: true

  - type: textarea
    id: process-inputs
    attributes:
      label: Information needed to start this process
      description: What data or inputs are required?
      placeholder: What information, documents, or data is needed to begin?
    validations:
      required: true

  - type: textarea
    id: process-outputs
    attributes:
      label: End result of this process
      description: What is produced when this process is complete?
      placeholder: What documents, data, or actions result from this process?
    validations:
      required: true

  - type: textarea
    id: exceptions
    attributes:
      label: Common exceptions or special cases
      description: What unusual scenarios occur in this process?
      placeholder: Describe any edge cases or special situations that need handling
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Technical Information

  - type: textarea
    id: current-tools
    attributes:
      label: Tools/systems currently used
      description: What software or platforms are used in this process?
      placeholder: |
        1. [Tool name] - Used for [purpose]
        2. [Tool name] - Used for [purpose]
        3. [Tool name] - Used for [purpose]
    validations:
      required: true

  - type: textarea
    id: data-formats
    attributes:
      label: Data types or file formats
      description: What data formats are involved in this process?
      placeholder: CSV, PDF, Excel, email, etc.
    validations:
      required: true

  - type: textarea
    id: integration-systems
    attributes:
      label: Systems needing integration
      description: What systems would the automation need to connect with?
      placeholder: List any systems that would need to be integrated
    validations:
      required: true

  - type: dropdown
    id: apis-available
    attributes:
      label: Do these systems have APIs?
      options:
        - Yes
        - No
        - Unsure
    validations:
      required: true

  - type: dropdown
    id: test-environment
    attributes:
      label: Is a test environment available?
      options:
        - Yes
        - No
        - Unsure
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Access Requirements

  - type: textarea
    id: system-access
    attributes:
      label: Systems requiring access
      description: What systems will we need credentials for?
      placeholder: |
        1. [System name] - Contact person: [name]
        2. [System name] - Contact person: [name]
        3. [System name] - Contact person: [name]
    validations:
      required: true

  - type: textarea
    id: security-requirements
    attributes:
      label: Security requirements
      description: Are there specific security protocols or considerations?
      placeholder: Compliance requirements, data sensitivity concerns, etc.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## People

  - type: input
    id: current-performers
    attributes:
      label: Who currently performs this process?
      description: Job titles or roles
    validations:
      required: true

  - type: input
    id: future-users
    attributes:
      label: Who will use the automated solution?
      description: Job titles or roles
    validations:
      required: true

  - type: input
    id: decision-makers
    attributes:
      label: Who can make decisions about this process?
      description: Who has authority to approve changes
    validations:
      required: true

  - type: input
    id: technical-contact
    attributes:
      label: Technical contact during implementation
      description: Who should we work with on technical matters?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Project Parameters

  - type: input
    id: timeline
    attributes:
      label: Desired completion timeline
      placeholder: "Q3 2025"
    validations:
      required: false

  - type: dropdown
    id: budget
    attributes:
      label: Budget range
      options:
        - Under $5,000
        - $5,000 - $10,000
        - $10,000 - $25,000
        - $25,000 - $50,000
        - Over $50,000
        - Not determined yet
    validations:
      required: false

  - type: dropdown
    id: maintenance
    attributes:
      label: Preferred maintenance approach
      options:
        - Internal team
        - Ongoing support contract
        - As-needed support
        - Other
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ## Success Criteria

  - type: textarea
    id: success
    attributes:
      label: What would make this automation project successful?
      description: How will you define success?
      placeholder: Describe the outcomes that would make this project worthwhile
    validations:
      required: true

  - type: textarea
    id: impact-measurement
    attributes:
      label: How will you measure the impact?
      description: What metrics will show success?
      placeholder: Time saved, error reduction, cost savings, etc.
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      description: Is there anything else we should know?
      placeholder: Any other details that would help us understand your needs
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description: By submitting this form, you agree to proceed with the discovery process
      options:
        - label: I understand this is a discovery form and does not constitute a commitment to proceed with development
          required: true
