name: "Daily ✅"
description: "A template for the team's daily checks"
type: Task
assignees:
  - "devinschumacher"
  - "francislabountyjr"

body:
  - type: markdown
    attributes:
      value: |
        ## Daily Checklist

        - [ ] Check serp-pipeline status/errors
        - [ ] Check serp-pipeline progress
        - [ ] Check github inbox
        - [ ] Update/close github issues
        
        ---
        **Instructions:**  
        1. Tick off each checklist item as it’s completed.  
        2. Add notes or updates in the field below.  
        3. Assign or mention relevant team members for follow-up tasks.

  - type: textarea
    id: description
    attributes:
      label: "Notes / Observations"
      description: "Add any relevant notes, updates, or blockers discovered during the daily checks."
    validations:
      required: false
