name: Feature ðŸŽ
description: >
  Use this template to request a new feature or enhancement.
  Please provide as much detail as possible to help us understand your request.
type: Feature

body:
  - type: textarea
    id: description

    attributes:
      description: "Add a description / user story of the issue, acceptance criteria, or details that help clarify the feature."
      placeholder: |
        1. Add a search bar to the top navigation.
        2. Users can enter keywords to see relevant article suggestions.
        3. Show up to 10 article results within 1 second, including titles and brief descriptions.
        4. Include links, screenshots, or any references (design inspiration, similar features, etc.).
