name: Question
description: Use this template to ask a question about the repo
title: "[question]: "
labels: ["question"]

body:
  - type: markdown
    attributes:
      label: "Question"
      value: "Ask your question & tag a specific person if relevant."
