name: SRE 🧪
description: Use this template to request tests, security, or code quality improvements (CICD/SRE)
labels: ["CICD", "SRE"]
type: Task

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
    validations:
      required: true
