name: CICD 🧪
description: Use this template to request test code to be written for an item.
labels: ["CICD, tests"]
type: Task

body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
    validations:
      required: true
