name: Tests Requested
description: Use this template to request test code to be written for an item.
title: "[cicd] write tests for item"
labels: ["CICD"]

body:
  - type: markdown
    attributes:
      value: |
        ## Tests Requested

        Thank you for requesting test code to be written. Please fill out the form below.

        *After the test code is written, the committer should upload a screenshot or file showing 100% coverage in the **Coverage Report** section below.*

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "Describe the item and any specific requirements for the test code."
      placeholder: "Provide additional details"
    validations:
      required: true

  - type: dropdown
    id: test_types
    attributes:
      label: "Type of Test"
      description: "Select the type of tests that need to be written."
      multiple: true
      options:
        - "unit"
        - "integration"
        - "E2E"
        - "unsure"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Coverage Report

        *To be completed by the committer after implementing the test code.*

  - type: input
    id: coverage_report
    attributes:
      label: "Coverage report/screenshot"
      description: "Upload a screenshot or report confirming test coverage on item on commit."
