name: Reusable Bug Notification Workflow

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      issue_number:
        required: true
        type: string
      issue_title:
        required: true
        type: string
      issue_url:
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🐛 *New Bug Report*",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🐛 *New Bug Report*\n*Repository:* ${{ inputs.repo_name }}\n*Issue:* <${{ inputs.issue_url }}|#${{ inputs.issue_number }}: ${{ inputs.issue_title }}>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
