name: Bug Alert to Slack

on:
  issues:
    types: [opened, labeled]
  workflow_dispatch:

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    if: |
      (github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'bug')) ||
      (github.event.action == 'labeled' && github.event.label.name == 'bug')
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🐛 New Bug Report",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "🐛 *New Bug Report*\n*Repository:* ${{ github.repository }}\n*Issue:* <${{ github.event.issue.html_url }}|#${{ github.event.issue.number }}: ${{ github.event.issue.title }}>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
