name: Bug Issue Alert

on:
  issues:
    types: [opened, labeled]

jobs:
  check-bug-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue for 'Type: Bug'
        if: |
          (github.event.action == 'opened' && contains(github.event.issue.labels.*.name, 'bug')) ||
          (github.event.action == 'labeled' && github.event.label.name == 'bug') ||
          (github.event.action == 'opened' && contains(github.event.issue.title, '[Bug]')) ||
          (github.event.action == 'opened' && github.event.issue.type == 'Bug')
        uses: serpcompany/.github/.github/workflows/bug-slack-notification.yml@main
        with:
          repo_name: ${{ github.repository }}
          issue_number: ${{ github.event.issue.number }}
          issue_title: ${{ github.event.issue.title }}
          issue_url: ${{ github.event.issue.html_url }}
        secrets:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
