name: Bug Alert

on:
  issues:
    types: [opened, edited]

jobs:
  check-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check issue for 'Type: Bug'
          id: check_issue
          uses: actions/github-script@v6
          with:
            script: |
              const issue = context.payload.issue;
              if (issue.body && issue.body.includes('Type: Bug')) {
                return { isBug: "true", issueUrl: issue.html_url };
              } else {
                return { isBug: "false" };
              }


      - name: Send notification to Slack
        if: steps.check_issue.outputs.isBug == 'true'
        uses: slackapi/slack-github-action@v1.19.0
        with:
          slack-message: 'A new bug has been reported: ${{ steps.check_issue.outputs.issueUrl }}'
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
