name: Deploy to Google Cloud Storage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    if: github.repository == 'serpcompany/allmoviestvshowslists.storage.googleapis.com'
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          package-manager: pnpm@latest
        env:
          NODE_OPTIONS: --max-old-space-size=131072

  deploy:
    needs: build
    runs-on: self-hosted
    if: github.repository == 'serpcompany/allmoviestvshowslists.storage.googleapis.com'
    steps:
      - name: Deploy to GCS
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "${GCP_SERVICE_ACCOUNT_KEY}" > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project $GCP_PROJECT_ID
          gsutil -m rsync -r public gs://$GCS_BUCKET_NAME
