name: Deploy to Google Cloud Storage

on:
  workflow_call:
    inputs:
      gcp_project_id:
        required: true
        type: string
      gcs_bucket_name:
        required: true
        type: string
      gcp_service_account_key:
        required: true
        type: string
      node_version:
        required: false
        default: '20'
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
      - name: Install, build, and upload your site
        uses: withastro/action@v1
        with:
          package-manager: pnpm@latest
        env:
          NODE_OPTIONS: --max-old-space-size=131072

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Deploy to GCS
        env:
          GCP_PROJECT_ID: ${{ inputs.gcp_project_id }}
          GCS_BUCKET_NAME: ${{ inputs.gcs_bucket_name }}
          GCP_SERVICE_ACCOUNT_KEY: ${{ inputs.gcp_service_account_key }}
        run: |
          echo "${GCP_SERVICE_ACCOUNT_KEY}" > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project $GCP_PROJECT_ID
          gsutil -m rsync -r public gs://$GCS_BUCKET_NAME
