name: Sync Github labels

on:
  workflow_dispatch:

jobs:
  manage-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Synchronize labels
        uses: julbme/gh-action-manage-label@v1.0.1
        with:
          from: .github/config/labels.yml
          skip_delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            
