# .github/workflows/sync-repo-labels.yml in serpcompany/.github
name: Sync Github Repo Labels

on:
  workflow_call:

jobs:
  manage-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout .github repository
        uses: actions/checkout@v2
        with:
          repository: serpcompany/.github
          path: .github-repo

      - name: Synchronize labels
        uses: julbme/gh-action-manage-label@v1.0.1
        with:
          from: .github-repo/.github/config/labels.yml
          skip_delete: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}