name: TruffleHog Secret Scanning

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run TruffleHog Secret Scan
      uses: trufflesecurity/trufflehog@main
      with:
        extra_args: --only-verified
